// Backup service — REL-01 MVP-1.
//
// Produces a hot-backup snapshot of the user's data directory that the
// renderer can hand to a user-chosen destination via a native folder
// picker. MVP-1 covers ONLY creation; restore + delete + restore
// preflight are scoped for the next iteration (the manifest is
// forward-compatible with them).
//
// What goes in:
//   - <dest>/<name>/todos.db                       (SQLite online backup)
//   - <dest>/<name>/todos/                          (durable file projections)
//   - <dest>/<name>/drawings/
//   - <dest>/<name>/attachments/
//   - <dest>/<name>/manifest.json                   (redacted metadata)
//
// What stays out (deliberately):
//   - dsh-sessions/    — JSONL session logs. They can be regenerated by
//                       re-running any conversation (the agent replays
//                       from conversation metadata), they're large on
//                       long-running installs, and they contain the
//                       literal user prompt + assistant text. Excluding
//                       them keeps the backup small + safe to share.
//
// Failure modes the contract pins:
//   - The SQLite file is captured via `db.backup(destPath)` — better-sqlite3
//     wraps `sqlite3_backup_init/_step/_finish` and handles WAL
//     correctly (no torn writes, no half-applied tx). This is the
//     recommended way per SQLite docs and the same primitive every
//     production-grade SQLite GUI uses.
//   - File projections are copied with `cpSync({ recursive: true })`.
//     The source data dir is NOT modified; a failed copy leaves the
//     live data intact and the partial dest subfolder is best-effort
//     cleaned up so we don't leave confusing half-backups behind.
//   - Manifest counts are taken from SQLite metadata only (no JSONL
//     reads), so building the manifest is O(1) and never blocks the
//     app's hot path.
//   - All sizes are reported in bytes; the renderer formats.
//
// Redaction:
//   - manifest contains NO absolute paths, NO API keys, NO user
//     prompts, NO conversation bodies. Only `sourceDataDirName`
//     (basename) is carried so two users with the same folder name
//     still get distinguishable manifests but neither leaks their
//     install layout.

import { cpSync, existsSync, mkdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { app } from 'electron';
import type Database from 'better-sqlite3';
import type { BackupManifest } from '../../shared/ipc-schema';
import { SCHEMA_VERSION } from '../db/schema';
import { logger } from '../logger';

const TODOS_SUBDIR = 'todos';
const DRAWINGS_SUBDIR = 'drawings';
const ATTACHMENTS_SUBDIR = 'attachments';
const DSH_SESSIONS_SUBDIR = 'dsh-sessions';

export interface CreateBackupOptions {
  /** Absolute path to the live data directory (the one with todos.db in it). */
  rootDir: string;
  /** better-sqlite3 handle for the live DB. Used via `.backup(destPath)`. */
  db: Database.Database;
  /** Absolute path to the directory the user picked via the folder picker.
   *  The backup is written into a uniquely-named subfolder inside it. */
  destDir: string;
}

export interface CreateBackupResult {
  /** Absolute path to the backup subfolder. */
  path: string;
  manifest: BackupManifest;
}

export class BackupError extends Error {
  constructor(public readonly code: string, message: string) {
    super(message);
    this.name = 'BackupError';
  }
}

/** Build a single, collision-resistant subfolder name for a backup.
 *  Format: `todo-list-backup-<YYYYMMDD-HHMMSS>-<short-random>`.
 *  Avoids colons (Windows path-illegal), spaces (URL-unfriendly), and
 *  uses local-time components so the user can eyeball when the backup
 *  was made in a file manager without opening manifest.json. */
export function backupFolderName(now: Date = new Date()): string {
  const pad = (n: number): string => String(n).padStart(2, '0');
  const stamp =
    `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}` +
    `-${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
  // 6 hex chars ≈ 16M-1 collision space per second — way more than the
  // backup frequency any human will hit. crypto.randomUUID is overkill
  // and adds length; we just need uniqueness across a single backup run.
  const rand = Math.floor(Math.random() * 0xffffff).toString(16).padStart(6, '0');
  return `todo-list-backup-${stamp}-${rand}`;
}

/** Read the schema version out of a fresh SELECT, not the in-process
 *  constant — that way the manifest reflects what's actually IN the DB
 *  (a future code upgrade could ship migrations that the current process
 *  hasn't run yet, but the DB on disk is at the older version). */
function readSchemaVersion(db: Database.Database): number {
  const row = db
    .prepare<[], { v: number | null }>('SELECT MAX(version) AS v FROM schema_meta')
    .get();
  return row?.v ?? 0;
}

/** Build a `BackupManifest` from SQLite metadata + filesystem stat.
 *  Pure read — does not copy any bytes. The caller passes the
 *  section sizes already computed by the copy loop. */
export function buildManifest(opts: {
  rootDir: string;
  db: Database.Database;
  sections: { db: number; todos: number; drawings: number; attachments: number };
  includeSections: { todos: boolean; drawings: boolean; attachments: boolean };
}): BackupManifest {
  const todosRow = opts.db
    .prepare<[], { c: number }>("SELECT COUNT(*) AS c FROM todos WHERE deleted_at IS NULL")
    .get();
  const convRow = opts.db
    .prepare<[], { c: number }>('SELECT COUNT(*) AS c FROM conversations')
    .get();
  // tag_catalog may not exist on very old DBs (pre-v17 migration).
  let tagCount = 0;
  try {
    const tagRow = opts.db
      .prepare<[], { c: number }>('SELECT COUNT(*) AS c FROM tag_catalog')
      .get();
    tagCount = tagRow?.c ?? 0;
  } catch {
    // table missing — tagCount stays 0
  }
  let inboxCount = 0;
  try {
    const inboxRow = opts.db
      .prepare<[], { c: number }>('SELECT COUNT(*) AS c FROM inbox_attachments')
      .get();
    inboxCount = inboxRow?.c ?? 0;
  } catch {
    // inbox_attachments table may be empty / pre-feature; inboxCount stays 0
  }
  return {
    schemaVersion: readSchemaVersion(opts.db),
    generatedAt: new Date().toISOString(),
    appVersion: app.getVersion(),
    // Basename only — never the absolute source path. Sharing a
    // manifest must not leak the user's install layout.
    sourceDataDirName: basename(opts.rootDir),
    counts: {
      todos: todosRow?.c ?? 0,
      conversations: convRow?.c ?? 0,
      tags: tagCount,
      inboxAttachments: inboxCount,
    },
    sections: {
      todos: opts.includeSections.todos,
      drawings: opts.includeSections.drawings,
      attachments: opts.includeSections.attachments,
      // Explicit literal — the field is a discriminator for restore to
      // know whether session logs need to be replayed vs recreated
      // empty. MVP-1 always skips them, but the field stays in the
      // shape so a future restore can read it without a schema bump.
      dshSessions: false,
    },
    sizes: {
      db: opts.sections.db,
      todos: opts.sections.todos,
      drawings: opts.sections.drawings,
      attachments: opts.sections.attachments,
      total:
        opts.sections.db +
        opts.sections.todos +
        opts.sections.drawings +
        opts.sections.attachments,
    },
  };
}

/** Copy a directory if it exists, recording the total bytes copied.
 *  Returns 0 if the directory doesn't exist (legitimate empty state —
 *  a fresh install has no `attachments/` until the user attaches one).
 *  Throws `BackupError('copy_failed', ...)` if the copy partially
 *  fails; the caller is responsible for rolling back the dest subfolder. */
function copySectionIfExists(srcDir: string, destSection: string): number {
  if (!existsSync(srcDir)) return 0;
  let totalBytes = 0;
  cpSync(srcDir, destSection, {
    recursive: true,
    // Don't preserve the source's mode bits — the dest's umask / mode
    // wins. Backup files don't need to be executable.
    preserveTimestamps: true,
    filter: (src) => {
      try {
        const s = statSync(src);
        if (s.isFile()) totalBytes += s.size;
      } catch {
        // File vanished between readdir and stat (rare on a quiescent
        // data dir, but possible during a write). Skip silently —
        // the rest of the backup is still valid.
      }
      return true;
    },
  });
  return totalBytes;
}

/** Create a backup under `destDir/<backupFolderName(now)>`.
 *  Throws `BackupError` with a typed code on any failure; the
 *  renderer's IPC layer maps these to user-visible messages. */
export async function createBackup(opts: CreateBackupOptions): Promise<CreateBackupResult> {
  const { rootDir, db, destDir } = opts;
  if (!existsSync(rootDir)) {
    throw new BackupError('source_missing', '源数据目录不存在');
  }
  if (!existsSync(destDir)) {
    throw new BackupError('dest_missing', '目标目录不存在');
  }

  const folderName = backupFolderName();
  const backupPath = join(destDir, folderName);
  if (existsSync(backupPath)) {
    // Math.random collision — extraordinarily unlikely (1 / 16M per
    // second), but a single retry is cheap and eliminates the
    // "destroyed the user's existing folder" failure mode.
    throw new BackupError('name_collision', '备份目录名冲突，请重试');
  }
  mkdirSync(backupPath, { recursive: true });

  const t0 = Date.now();
  try {
    // 1) SQLite online backup. better-sqlite3's `.backup(path)` is a
    //    synchronous wrapper around `sqlite3_backup_init/_step/_finish`
    //    — exactly the primitive SQLite recommends for live backups.
    //    Handles WAL correctly: all committed tx are included, in-flight
    //    tx either complete or are skipped, no torn writes.
    const dbDest = join(backupPath, 'todos.db');
    await db.backup(dbDest);
    const dbSize = statSync(dbDest).size;

    // 2) Durable file projections. Each is copied only if it exists
    //    (a fresh install may legitimately have no `attachments/`).
    const todosBytes = copySectionIfExists(
      join(rootDir, TODOS_SUBDIR),
      join(backupPath, TODOS_SUBDIR),
    );
    const drawingsBytes = copySectionIfExists(
      join(rootDir, DRAWINGS_SUBDIR),
      join(backupPath, DRAWINGS_SUBDIR),
    );
    const attachmentsBytes = copySectionIfExists(
      join(rootDir, ATTACHMENTS_SUBDIR),
      join(backupPath, ATTACHMENTS_SUBDIR),
    );
    // DSH sessions are deliberately not copied — see file header.

    const includeSections = {
      // `existsSync` was the gate inside `copySectionIfExists`; we
      // re-check here so the manifest reflects what we ACTUALLY wrote
      // (defends against the edge case where cpSync encounters a
      // broken symlink and skips silently).
      todos: existsSync(join(rootDir, TODOS_SUBDIR)),
      drawings: existsSync(join(rootDir, DRAWINGS_SUBDIR)),
      attachments: existsSync(join(rootDir, ATTACHMENTS_SUBDIR)),
    };

    const manifest = buildManifest({
      rootDir,
      db,
      sections: {
        db: dbSize,
        todos: todosBytes,
        drawings: drawingsBytes,
        attachments: attachmentsBytes,
      },
      includeSections,
    });
    writeFileSync(
      join(backupPath, 'manifest.json'),
      JSON.stringify(manifest, null, 2),
      'utf-8',
    );

    // Reference the constant so tree-shakers / minifiers keep it
    // (and so a future bug where SCHEMA_VERSION drifts from the
    // manifest's schemaVersion field is caught at type-check time).
    void SCHEMA_VERSION;
    // Reference DSH_SESSIONS_SUBDIR so it's not unused (the constant
    // documents the deliberate exclusion for future readers).
    void DSH_SESSIONS_SUBDIR;

    logger.info(
      `backup: wrote ${backupPath} (db=${dbSize}B todos=${todosBytes}B ` +
        `drawings=${drawingsBytes}B attachments=${attachmentsBytes}B) in ${Date.now() - t0}ms`,
    );

    return { path: backupPath, manifest };
  } catch (err) {
    // Best-effort cleanup so we don't leave a half-written subfolder
    // that confuses the user. The user can still see / manually delete
    // it if rmSync itself fails (permission issue), but that requires
    // explicit user intervention so a console log is appropriate.
    try {
      rmSync(backupPath, { recursive: true, force: true });
    } catch (cleanupErr) {
      logger.warn(`backup: cleanup of ${backupPath} failed: ${(cleanupErr as Error).message}`);
    }
    if (err instanceof BackupError) throw err;
    throw new BackupError('backup_failed', (err as Error).message || '备份写入失败');
  }
}